const stage=document.getElementById('stage'),shell=document.getElementById('shell'),ignite=document.getElementById('ignite'),shift=document.getElementById('shift'),state=document.getElementById('state'),sub=document.getElementById('sub');
let mode=1,awake=false,progress=18;
function aim(x,y){const r=stage.getBoundingClientRect(),px=(x-r.left)/r.width,py=(y-r.top)/r.height;stage.style.setProperty('--mx',px*100+'%');stage.style.setProperty('--my',py*100+'%');shell.style.transform=`perspective(950px) rotateX(${(0.5-py)*8}deg) rotateY(${(px-.5)*12}deg)`}
stage.addEventListener('mousemove',e=>aim(e.clientX,e.clientY));stage.addEventListener('mouseleave',()=>shell.style.transform='perspective(950px) rotateX(0) rotateY(0)');stage.addEventListener('touchmove',e=>{const t=e.touches[0];if(t)aim(t.clientX,t.clientY)},{passive:true});
ignite.addEventListener('click',()=>{awake=!awake;stage.classList.toggle('awake',awake);ignite.textContent=awake?'STABILIZE':'IGNITE';state.textContent=awake?'OVERDRIVE':'STABLE';sub.textContent=awake?'Core output unlocked. Reactive bloom, spectral drift and pulse synchronization are active.':'Move your cursor. Ignite the core. Cycle the spectrum. Everything here is live HTML, CSS and JavaScript.';progress=awake?86:18;shell.style.setProperty('--p',progress+'%')});
shift.addEventListener('click',()=>{mode=mode%3+1;stage.dataset.mode=mode;progress=mode===1?34:mode===2?61:78;shell.style.setProperty('--p',progress+'%');state.textContent=['','VIOLET','SOLAR','BIO-LUME'][mode]});
const c=document.getElementById('stars'),ctx=c.getContext('2d');let W,H,DPR,stars=[];
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=c.clientWidth;H=c.clientHeight;c.width=W*DPR;c.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);stars=Array.from({length:Math.floor(W*H/8500)},()=>({x:Math.random()*W,y:Math.random()*H,z:.2+Math.random()*.8,r:.35+Math.random()*1.3,p:Math.random()*Math.PI*2}))}
function draw(){ctx.clearRect(0,0,W,H);for(const s of stars){s.p+=.01+s.z*.012;s.y+=.025+s.z*.05;if(s.y>H+3)s.y=-3;const a=.18+(.5+.5*Math.sin(s.p))*.72;ctx.beginPath();ctx.arc(s.x,s.y,s.r*(.7+s.z*.6),0,Math.PI*2);ctx.fillStyle=`rgba(230,246,255,${a})`;ctx.shadowBlur=8*s.z;ctx.shadowColor='rgba(127,222,255,.8)';ctx.fill()}ctx.shadowBlur=0;requestAnimationFrame(draw)}
addEventListener('resize',resize);resize();requestAnimationFrame(draw);shell.style.setProperty('--p','18%');